# -*- coding: utf-8 -*-
"""P-107

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1moZiy4ieQ9AL9uns1uNsaTtxRm7I60pX
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import csv
import plotly.express as px

df = pd.read_csv('data.csv')

Mean = df.groupby(['student_id','level'], as_index = False)['attempt'].mean()

fig = px.scatter(Mean, x = 'student_id', y = 'level', size = 'attempt',color= 'attempt')
fig.show()